version: 2
updates:

    - package-ecosystem: "bundler"
      directory: "/"
      schedule:
        interval: "daily"
      reviewers:
        - yammmt

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "daily"
      reviewers:
        - yammmt
